# Generated by Django 6.0.5 on 2026-05-08 22:52

import apps.claims.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.CharField(default=apps.claims.models.generate_claim_id, max_length=15, primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(db_index=True, max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MANUAL_REVIEW', 'Manual Review'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('reason_text', models.TextField()),
                ('final_decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('manual_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('DAMAGE_PHOTO', 'Damage Photo'), ('INVOICE', 'Invoice')], max_length=15)),
                ('file', models.FileField(upload_to='claims/')),
                ('image_hash', models.CharField(blank=True, max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='claims.claim')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_matched', models.BooleanField(default=False)),
                ('order_in_window', models.BooleanField(default=False)),
                ('damage_detected', models.BooleanField(default=False)),
                ('damage_type', models.CharField(blank=True, max_length=20)),
                ('damage_severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('damage_confidence', models.FloatField(default=0.0)),
                ('is_authentic', models.BooleanField(default=False)),
                ('authenticity_confidence', models.FloatField(default=0.0)),
                ('authenticity_flags', models.JSONField(default=list)),
                ('invoice_ocr_raw_text', models.TextField(blank=True)),
                ('invoice_order_id_found', models.CharField(blank=True, max_length=20)),
                ('invoice_date_found', models.CharField(blank=True, max_length=30)),
                ('invoice_matched', models.BooleanField(default=False)),
                ('duplicate_image_found', models.BooleanField(default=False)),
                ('duplicate_claim_id', models.CharField(blank=True, max_length=15)),
                ('recommendation', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MANUAL_REVIEW', 'Manual Review')], max_length=15)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='claims.claim')),
            ],
        ),
    ]
