# Generated by Django 6.0.5 on 2026-05-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('current_state', models.CharField(choices=[('INITIAL', 'Initial'), ('AWAITING_ORDER_ID', 'Awaiting Order ID'), ('AWAITING_DAMAGE_PHOTO', 'Awaiting Damage Photo'), ('AWAITING_INVOICE', 'Awaiting Invoice'), ('DONE', 'Done'), ('ABANDONED', 'Abandoned')], default='INITIAL', max_length=30)),
                ('context_data', models.JSONField(default=dict)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claims.claim')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=10)),
                ('message_body', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('twilio_message_sid', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_bot.conversationsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
